package restaurant

var WaitersNames = [...]string{
	"Mario",
	"Luigi",
	"Princess Peach",
	"Yoshi",
	"Bowser",
	"Donkey Kong",
	"Toad",
	"Koopa Troopa",
	"Princess Daisy",
	"Wario",
	"Waluigi",
	"Rosalina",
	"Toadette",
	"Baby Mario",
	"Baby Luigi",
	"Metal Mario",
	"Dry Bones",
	"King Boo",
	"Lakitu",
	"Shy Guy",
	"Bowser Jr.",
	"Donkey Kong Jr.",
	"Cat Peach",
	"Tanooki Mario",
	"Pink Gold Peach",
	"Inkling Boy",
	"Inkling Girl",
	"Link",
	"Isabelle",
	"Villager (Male)",
	"Villager (Female)",
}

var OrdersNames = [...]string{
	"Bacalhau à Brás",
	"Caldo Verde",
	"Arroz de Marisco",
	"Cozido à Portuguesa",
	"Bifanas",
	"Carne de Porco à Alentejana",
	"Bitoque",
	"Polvo à Lagareiro",
	"Sardinhas Assadas",
	"Açorda",
	"Pastéis de Nata",
	"Alheira de Mirandela",
	"Arroz de Pato",
	"Leitão da Bairrada",
}

var ChefNames = [...]string{
	"Remy",
	"Linguini",
	"Colette",
	"Gusteau",
	"Anton Ego",
	"Django",
	"Emile",
	"Skinner",
	"Horst",
	"Lalo",
	"Pompidou",
	"Talon Labarthe",
}
